<div style="background-color: #ffA500; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">Book Recommendation System </h1>
</div>

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;"> What is a Recommendation System? </h1>
</div>


<div style="background-color: #008000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 22px;">The goal of recommendation systems is to anticipate users' preferences and suggest products that are most likely to be of interest to them.</h1>
</div>

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">Methods for Recomendation System </h1>
</div>


<div style="background-color: #008000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 22px;">      
        1.Collaborative Filtering<br>
        2.Content-Based Filtering<br>
        3.Hybrid Models</h1>
</div>

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">Load Data </h1>
</div>

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from scipy.sparse import csr_matrix

In [2]:
books = pd.read_csv('/kaggle/input/book-recommendation-dataset/Books.csv')
users = pd.read_csv('/kaggle/input/book-recommendation-dataset/Users.csv')
ratings = pd.read_csv('/kaggle/input/book-recommendation-dataset/Ratings.csv')

/tmp/ipykernel_18/2910231406.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('/kaggle/input/book-recommendation-dataset/Books.csv')


In [3]:
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press   
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">About the dataset </h1>
</div>


<div style="background-color: #66bbf1; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px; color: white;">Books Dataset</h1>
    <p style="color: white; font-size: 18px;">
        Contains basic information regarding the books. (270k+ books)
        <br><br>
        <b>Columns:</b>
        <br>
        <ul>
            <li>ISBN</li>
            <li>Title</li>
            <li>Author</li>
            <li>Year of publication</li>
            <li>Publisher</li>
        </ul>
    </p>
</div>

<div style="background-color: #66bbf1; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px; color: white;">Rating Dataset</h1>
    <p style="color: white; font-size: 18px;">
        Contains all of the user rating information. (1 million+ ratings)
        <br><br>
        <b>Columns:</b>
        <br>
        <ul>
            <li>UserID</li>
            <li>ISBN</li>
            <li>Rating (1-10, 10 being the highest)</li>
        </ul>
    </p>
</div>

<div style="background-color: #66bbf1; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px; color: white;">Users Dataset</h1>
    <p style="color: white; font-size: 18px;">
        Contains basic information regarding the reader. (275k+ users)
        <br><br>
        <b>Columns:</b>
        <br>
        <ul>
            <li>UserID</li>
            <li>Location</li>
            <li>Age</li>
        </ul>
    </p>
</div>

<div style="background-color: #66bbf1; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 22px;">Source: Kaggle Dataset</h1>
</div>

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">Merge on basis of ISBN </h1>
</div>


In [6]:
ratings_with_name = ratings.merge(books, on='ISBN')
ratings_with_name

User-ID        ISBN  Book-Rating  \
0         276725  034545104X            0   
1         276726  0155061224            5   
2         276727  0446520802            0   
3         276729  052165615X            3   
4         276729  0521795028            6   
...          ...         ...          ...   
1031131   276704  0876044011            0   
1031132   276704  1563526298            9   
1031133   276706  0679447156            0   
1031134   276709  0515107662           10   
1031135   276721  0590442449           10   

                                                Book-Title        Book-Author  \
0                                     Flesh Tones: A Novel         M. J. Rose   
1                                         Rites of Passage         Judith Rae   
2                                             The Notebook    Nicholas Sparks   
3                                           Help!: Level 1      Philip Prowse   
4        The Amsterdam Connection : Level 4 (Cambridge ...        Sue Leather   
...                                                    ...                ...   
1031131  Edgar Cayce on the Akashic Records: The Book o...  Kevin J. Todeschi   
1031132  Get Clark Smart : The Ultimate Guide for the S...       Clark Howard   
1031133  Eight Weeks to Optimum Health: A Proven Progra...        Andrew Weil   
1031134   The Sherbrooke Bride (Bride Trilogy (Paperback))  Catherine Coulter   
1031135                                  Fourth Grade Rats     Jerry Spinelli   

        Year-Of-Publication  \
0                      2002   
1                      2001   
2                      1996   
3                      1999   
4                      2001   
...                     ...   
1031131                1998   
1031132                2000   
1031133                1997   
1031134                1996   
1031135                1996   

                                                 Publisher  \
0                                         Ballantine Books   
1                                                   Heinle   
2                                             Warner Books   
3                               Cambridge University Press   
4                               Cambridge University Press   
...                                                    ...   
1031131  A.R.E. Press (Association of Research &amp; Enlig   
1031132                                   Longstreet Press   
1031133                                    Alfred A. Knopf   
1031134                                         Jove Books   
1031135                                         Scholastic   

                                               Image-URL-S  \
0        http://images.amazon.com/images/P/034545104X.0...   
1        http://images.amazon.com/images/P/0155061224.0...   
2        http://images.amazon.com/images/P/0446520802.0...   
3        http://images.amazon.com/images/P/052165615X.0...   
4        http://images.amazon.com/images/P/0521795028.0...   
...                                                    ...   
1031131  http://images.amazon.com/images/P/0876044011.0...   
1031132  http://images.amazon.com/images/P/1563526298.0...   
1031133  http://images.amazon.com/images/P/0679447156.0...   
1031134  http://images.amazon.com/images/P/0515107662.0...   
1031135  http://images.amazon.com/images/P/0590442449.0...   

                                               Image-URL-M  \
0        http://images.amazon.com/images/P/034545104X.0...   
1        http://images.amazon.com/images/P/0155061224.0...   
2        http://images.amazon.com/images/P/0446520802.0...   
3        http://images.amazon.com/images/P/052165615X.0...   
4        http://images.amazon.com/images/P/0521795028.0...   
...                                                    ...   
1031131  http://images.amazon.com/images/P/0876044011.0...   
1031132  http://images.amazon.com/images/P/1563526298.0...   
1031133  http://images.amazon.com/images/P/0679447156.0...   
1031134  htt

<div style="background-color: #008000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 22px;"> Merges the ratings with book details and filters users who have rated more than 50 books and books rated at least 10 times.</h1>
</div>

In [7]:
# Filter users who have rated more than 50 books
user_ratings_count = ratings_with_name.groupby('User-ID').count()['Book-Rating']
active_users = user_ratings_count[user_ratings_count > 50].index
filtered_ratings = ratings_with_name[ratings_with_name['User-ID'].isin(active_users)]
# Filter books that have been rated at least 10 times
book_ratings_count = filtered_ratings.groupby('Book-Title').count()['Book-Rating']
popular_books = book_ratings_count[book_ratings_count >= 10].index
final_ratings = filtered_ratings[filtered_ratings['Book-Title'].isin(popular_books)]
final_ratings

User-ID        ISBN  Book-Rating  \
298       276925  002542730X           10   
299       276925  0060520507            0   
300       276925  0060930934            0   
301       276925  0060951303            0   
303       276925  0140327592            0   
...          ...         ...          ...   
1031101   276688  0836218655           10   
1031102   276688  0836236688           10   
1031104   276688  1551669315            6   
1031105   276688  1575660792            7   
1031106   276688  1580600506            0   

                                                Book-Title        Book-Author  \
298      Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner   
299          Sushi for Beginners : A Novel (Keyes, Marian)       Marian Keyes   
300              Wasted : A Memoir of Anorexia and Bulimia   Marya Hornbacher   
301                              La casa de los espíritus     Isabel Allende   
303                                                Matilda         Roald Dahl   
...                                                    ...                ...   
1031101                                     Wiener Dog Art        Gary Larson   
1031102  Dilbert: Seven Years Of Highly Defective Peopl...        Scott Adams   
1031104                                     The Third Wife  Jasmine Cresswell   
1031105                                        Gray Matter    Shirley Kennett   
1031106                                     The Fallen Man     Tony Hillerman   

        Year-Of-Publication                          Publisher  \
298                    1994          John Wiley &amp; Sons Inc   
299                    2003                     William Morrow   
300                    1999                          Perennial   
301                    1995                               Rayo   
303                    1990                 Viking Penguin Inc   
...                     ...                                ...   
1031101                1990          Andrews McMeel Publishing   
1031102                1997          Andrews McMeel Publishing   
1031104                2002                               Mira   
1031105                1996  Kensington Publishing Corporation   
1031106                1996                      HarperCollins   

                                               Image-URL-S  \
298      http://images.amazon.com/images/P/002542730X.0...   
299      http://images.amazon.com/images/P/0060520507.0...   
300      http://images.amazon.com/images/P/0060930934.0...   
301      http://images.amazon.com/images/P/0060951303.0...   
303      http://images.amazon.com/images/P/0140327592.0...   
...                                                    ...   
1031101  http://images.amazon.com/images/P/0836218655.0...   
1031102  http://images.amazon.com/images/P/0836236688.0...   
1031104  http://images.amazon.com/images/P/1551669315.0...   
1031105  http://images.amazon.com/images/P/1575660792.0...   
1031106  http://images.amazon.com/images/P/1580600506.0...   

                                               Image-URL-M  \
298      http://images.amazon.com/images/P/002542730X.0...   
299      http://images.amazon.com/images/P/0060520507.0...   
300      http://images.amazon.com/images/P/0060930934.0...   
301      http://images.amazon.com/images/P/0060951303.0...   
303      http://images.amazon.com/images/P/0140327592.0...   
...                                                    ...   
1031101  http://images.amazon.com/images/P/0836218655.0...   
1031102  http://images.amazon.com/images/P/0836236688.0...   
1031104  http://images.amazon.com/images/P/1551669315.0...   
1031105  http://images.amazon.com/images/P/1575660792.0...   
1031106  http://images.amazon.com/images/P/1580600506.0...   

                                               Image-URL-L  
298      http://images.amazon.com/images/P/002542730X.0...  
299      http://images.amazon.com/images/P/0060520507.0...  
300      http://images.amazon

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">User-Item Pivot Table </h1>
</div>

<div style="background-color: #008000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 22px;"> Making the table which consist book-title in row,user in column and
ratings are values.</h1>
</div>

In [8]:
pivot_table = final_ratings.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating')
pivot_table.fillna(0, inplace=True)
pivot_table

User-ID                                             243     254     507     \
Book-Title                                                                   
 Murder of a Sleeping Beauty (Scumble River Mys...     0.0     0.0     0.0   
 Q-Space (Star Trek The Next Generation, Book 47)      0.0     0.0     0.0   
'Salem's Lot                                           0.0     0.0     0.0   
01-01-00: The Novel of the Millennium                  0.0     0.0     0.0   
1,000 Places to See Before You Die                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   
\Surely You're Joking, Mr. Feynman!\": Adventur...     0.0     0.0     0.0   
e                                                      0.0     0.0     0.0   
one hundred years of solitude                          0.0     0.0     0.0   
stardust                                               0.0     0.0     0.0   

User-ID                                             638     643     741     \
Book-Title                                                                   
 Murder of a Sleeping Beauty (Scumble River Mys...     0.0     0.0     0.0   
 Q-Space (Star Trek The Next Generation, Book 47)      0.0     0.0     0.0   
'Salem's Lot                                           0.0     0.0     0.0   
01-01-00: The Novel of the Millennium                  0.0     0.0     0.0   
1,000 Places to See Before You Die                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   
\Surely You're Joking, Mr. Feynman!\": Adventur...     0.0     0.0     0.0   
e                                                      0.0     0.0     0.0   
one hundred years of solitude                          0.0     0.0     0.0   
stardust                                               0.0     0.0     0.0   

User-ID                                             882     929     1211    \
Book-Title                                                                   
 Murder of a Sleeping Beauty (Scumble River Mys...     0.0     0.0     0.0   
 Q-Space (Star Trek The Next Generation, Book 47)      0.0     0.0     0.0   
'Salem's Lot                                           0.0     0.0     0.0   
01-01-00: The Novel of the Millennium                  0.0     0.0     0.0   
1,000 Places to See Before You Die                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   
\Surely You're Joking, Mr. Feynman!\": Adventur...     0.0     0.0     0.0   
e                                                      0.0     0.0     0.0   
one hundred years of solitude                          0.0     0.0     0.0   
stardust                                               0.0     0.0     0.0   

User-ID                                             1424    ...  277928  \
Book-Title                                                  ...           
 Murder of a Sleeping Beauty (Scumble River Mys...     0.0  ...     0.0   
 Q-Space (Star Trek The Next Generation, Book 47)      0.0  ...     0.0   
'Salem's Lot                                           0.0  ...     0.0   
01-01-00: The Novel of the Millennium                  0.0  ...     0.0   
1,000 Places to See Before You Die                     0.0  ...     0.0   
...                                                    ...  ...     ...   
\O\" Is for Outlaw"                                    0.0  ...     0.0   
\Surely You're Joking, Mr. Feynman!\": Adventur...     0.0  ...     0.0   
e                                                      0.0  ...     0.0   
one hundred years of solitude                          0.0  ...     0.0   
stardust                                               

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">Recommendation using Cosine similarity
</div>

<div style="background-color: #ffA500; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px; color: white;">Cosine Similarity in Collaborative Filtering</h1>
    <p style="color: white; font-size: 18px;">
        Cosine Similarity is a measure of similarity used in collaborative filtering.
        <br>
        It works by measuring the cosine of the angle between two vectors.
        <br>
        In this case, the vectors represent the behavior of two users, and the cosine similarity measures how similar their behavior is.
    </p>
</div>


In [9]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(pivot_table)

In [10]:
def recommend(book_name):
    index = np.where(pivot_table.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x: x[1], reverse=True)[1:6]
    for i in similar_items:
        book_title = pivot_table.index[i[0]]
        print(book_title)



In [11]:
recommend('Animal Farm')

1984
The Republic of Love
Vintage Stuff
No Comebacks
The crow road


<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">KNN(Brute Algorithm and Cosine Similarity)</h1>
</div>

<div style="background-color: #66bbf1; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px; color: white;">Brute-Force Approach in KNN</h1>
    <p style="color: white; font-size: 18px;">
        The brute-force approach in KNN focuses on the training phase, where the distances between data points are calculated and stored.
        <br><br>
        During the prediction phase, these precomputed distances are leveraged to find the nearest neighbors efficiently.
        <br><br>
        <b>Steps:</b>
        <br>
        1. Converts the pivot table into a sparse utility matrix using `csr_matrix` from SciPy.
        <br>
        2. Initializes a `NearestNeighbors` model using the brute-force algorithm (`algorithm='brute'`), comparing all pairs of points for nearest neighbor computation, suitable for smaller datasets.
        <br>
        3. Employs cosine similarity (`metric='cosine'`) to measure the cosine of the angle between vectors, facilitating similarity calculations among different items in the utility matrix.
    </p>
</div>

In [12]:
# Create a utility matrix from final_ratings pivot table
pt_matrix = csr_matrix(pivot_table.values)
print(pt_matrix.toarray())
# Convert the pivot table into a sparse matrix
model_knn = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn.fit(pt_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


NearestNeighbors(algorithm='brute', metric='cosine')

<div style="background-color: #ff0000; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">Function for Recomendation</h1>
</div>

In [13]:
def recommend(book):
    try:
        query_index = pivot_table.index.get_loc(book)
        distances, indices = model_knn.kneighbors(pt_matrix[query_index], n_neighbors=6)

        print(f"Recommendations for '{pivot_table.index[query_index]}':")
        for i in range(1, len(distances.flatten())):
            print(f"{i}: {pivot_table.index[indices.flatten()[i]]}")

    except KeyError:
        print(f"The book '{book}' is not found in the dataset.")
        similar_books = find_similar_books(book)

        if similar_books:
            print("*********************************************")
            print(f"Did you mean one of these books?")
            for i, similar_book in enumerate(similar_books, start=1):
                print(f"{i}: {similar_book}")
        else:
            print(f"No similar books found. Please try a different book name.")



def find_similar_books(book):
    similar_books = [b for b in pivot_table.index if book.lower() in b.lower()]
    return similar_books[:10] if similar_books else []


    
# while True:
#     print("*********************************************")
#     book_name = input("Enter the Book Name (Type 'exit' to stop): ")

#     if book_name.lower() == 'exit':
#         print("Exiting the recommendation system.")
#         print("*********************************************")
#         break

#     recommend(book_name)

<div style="background-color: #ffA500; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px;">If you want to learn more about this project check out my full Report on my Github. </h1>
</div>


Github : https://github.com/Pruthvik-Machhi/Book-Recommendation-System

<div style="background-color: #66bbf1; padding: 20px; border-radius: 10px;">
    <h1 style="text-align: left; font-size: 32px; color: white;">Thanks for exploring my notebook. Upvote if you like the work. Also, Give your feedback in comments.</h1>
    <p style="color: white; font-size: 18px;">
    </p>
</div>